version: "3.8"
services:
  app:
    build: .
    ports:
      - "8091:8091"
    command: "java -jar ktor-sample-service-all.jar"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8091 && echo 'OK'"]
      interval: 5s
      timeout: 2s
      retries: 10
  zap:
    image: "owasp/zap2docker-weekly"
    command: "zap-api-scan.py -t http://app:8091/apidocs/openapi.json -f openapi"
    depends_on:
      app:
        condition: service_healthy
